### PR TITLE
Feat: Notary website redesign

### LINKED ISSUE #112: Notary/new: Style the buttons to match with new design
cc: @hamees-sayed

### LINKED ISSUE #113: Notary/new: Create and style the feature card component
cc: @hamees-sayed

### PR DESCRIPTION
**Pull request by thisisobate**
Duplicate of #110 
Fixes #113 
Fixes  #112
**Todos**
- [x] Flesh out hero section
- [x] [Style the buttons](https://github.com/notaryproject/notaryproject.dev/issues/112) - assigned to Hamees
- [x] [Create feature card component](https://github.com/notaryproject/notaryproject.dev/issues/113) - assigned to Hamees
- [x] Create layout/structure using plain HTML
- [x] Style page
- [x] Implement mobile responsiveness
- [x] Convert HTML to Hugo templates
- [x] Update the landing page based on the latest change
- [x] Update content with real data
- [x] Add two links to two buttons
- [x] Move the logo to corner at the top left
- [x] Change Resources to Blog for the first version
- [x] Pull the updates from the latest main branch for /doc
- [x] Clean code
  - [x] fix font sizing
  - [x] remove redundant code
  - [x] maintain consistent units

**Follow-up PR**
- [ ] Make the “News & Blogs” section to be dynamic
- [ ] Split file into components

### CODE REVIEW

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Review by toddysm — APPROVED** [review]
LGTM

**Comment by ArafatAbdussalam** [comment]
Hi @FeynmanZhou I am an LFX applicant and I will like to work on this project

**Comment by Sukhendu2002** [comment]
Hello @FeynmanZhou, my name is Sukhendu Sekhar Guria, and I am an LFX applicant. I am interested in contributing to this project. Could you please provide me with any helpful resources to get started? Thank you.

**Pull request merged**
