### PR TITLE
Fixed text overflow from navbar in mobile version.

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@Prakhar-Shankar Thanks for your contribution! Could you check the error log and fix the build problem? https://app.netlify.com/sites/notarydev/deploys/645fcc54f73c530008855798#L133

**Comment by Prakhar-Shankar** [comment]
> @Prakhar-Shankar Thanks for your contribution! Could you check the error log and fix the build problem? https://app.netlify.com/sites/notarydev/deploys/645fcc54f73c530008855798#L133

Yes I am trying to solve these issues.

**Comment by hugo-sid** [comment]
> Can you please guid me through this.

Sure. 

From the log:

```shell
11:14:24 PM: htmltest started at 05:44:24 on public
11:14:24 PM: ========================================================================
11:14:24 PM: docs/cli-reference/notation_login/index.html
11:14:24 PM:   target does not exist --- docs/cli-reference/notation_login/index.html --> /assets/icons/rocket-icon.svg
11:14:24 PM: docs/cli-reference/notation_inspect/index.html
11:14:24 PM:   target does not exist --- docs/cli-reference/notation_inspect/index.html --> /assets/icons/rocket-icon.svg
11:14:24 PM: docs/cli-reference/notation_certificate_show/index.html
11:14:24 PM:   target does not exist --- docs/cli-reference/notation_certificate_show/index.html --> /assets/icons/rocket-icon.svg
```
The deploy is failing when HTML test is run. Some links (assets) seems to be missing.
Particularly, `/assets/icons/rocket-icon.svg` seems to be missing.

I think this can be fixed if you change the following line in `layouts/partials/banner.html`,

from:

```html
<span><img src="/notaryproject.dev/assets/icons/rocket-icon.svg" class="img-container-xxxsm" alt="star icon"></span>
```
to:

```go
{{ $rocketIcon := resources.Get "icons/rocket-icon.svg" }}
<img
src="{{ $rocketIcon.RelPermalink }}"
class="img-container-xxxsm"
alt="star icon"
/></span>
```

**Comment by hugo-sid** [comment]
Great job @Prakhar-Shankar. The Netlify build seems to succeed now.

## Few more changes

## Change 1: fix commit signing issue
As you may be aware, this project requires signed commits. One check is failing due to incorrectly signed commits.  Further details (including instructions to fix this) are available here: https://github.com/notaryproject/notaryproject.dev/pull/205/checks?check_run_id=13518340628
Can you try to fix this, and push again?

## Change 2: change link to homepage

In file `layouts/partials/navbar.html`, could you change `/` to `{{ .Site.Home.RelPermalink }}` ?

### Reasoning

The appropriate way to include a link to homepage in Hugo can be done using `{{ .Site.Home.RelPermalink }}` .
You can read more about URL management in Hugo documentation here: https://gohugo.io/content-management/urls/ .

The `/` works as of now & there are no problems. However, I guess, this may lead to errors if the site grows complex (may or may not be true).

**Comment by Prakhar-Shankar** [comment]
> > Can you please guid me through this.
> 
> @Prakhar-Shankar, here is my analysis.
> 
> ## Problem
> From the log:
> 
> ```shell
> 11:14:24 PM: htmltest started at 05:44:24 on public
> 11:14:24 PM: ========================================================================
> 11:14:24 PM: docs/cli-reference/notation_login/index.html
> 11:14:24 PM:   target does not exist --- docs/cli-reference/notation_login/index.html --> /assets/icons/rocket-icon.svg
> 11:14:24 PM: docs/cli-reference/notation_inspect/index.html
> 11:14:24 PM:   target does not exist --- docs/cli-reference/notation_inspect/index.html --> /assets/icons/rocket-icon.svg
> 11:14:24 PM: docs/cli-reference/notation_certificate_show/index.html
> 11:14:24 PM:   target does not exist --- docs/cli-reference/notation_certificate_show/index.html --> /assets/icons/rocket-icon.svg
> ```
> 
> The deploy is failing when `htmltest` is run. Some links (assets) seems to be missing. Particularly, the `/assets/icons/rocket-icon.svg` file seems to be missing.
> 
> This causes the make utility (which is responsible for running htmltest) return this error:
> 
> ```shell
> 11:14:25 PM: make: *** [Makefile:18: check-links] Error 1
> ```
> 
> Consequently the Netlify build fails since the build command resulted in an error.
> 
> ## Solution
> I think this can be fixed if you take the following steps.
> 
> ### Step1: Use Hugo's ` resources.Get` method to load the icon
> Can you change the following line in `layouts/partials/banner.html`
> 
> from:
> 
> ```
> <span>star icon</span>
> ```
> 
> to:
> 
> ```go
> {{ $rocketIcon := resources.Get "icons/rocket-icon.svg" }}
>  src="{{ $rocketIcon.RelPermalink }}"
> class="img-container-xxxsm"
> alt="star icon"
> /></span>
> ```
> 
> ### Step 2: Push the changes to your fork
> This should trigger a new Netlify deploy (preview).
> 
> ## Reasoning
> In short:
> 
> In order to get URL to a file stored in the assets folder, you have to use the Hugo `resources.Get` method. More on this is available in the documentation here: [Find resources in assets gohugo.io](https://gohugo.io/hugo-pipes/introduction/#find-resources-in-assets).

Thanks for helping me out it passed the checks, the last problem is DCO check which is failing everytime. I have tried many times but it is not working. I will be greatful if you can also help me through DCO issue.

**Comment by hugo-sid** [comment]
>Thanks for helping me out it passed the checks, the last problem is DCO check which is failing every time. I have tried many times but it is not working. 

You are welcome @Prakhar-Shankar.

> I will be grateful if you can also help me through DCO issue.

Sure. Please have a look at these videos which explain in detail, how to configure signed commits:

1. [Signing and Verifying Git Commits on the Command Line and GitHub - YouTube](https://youtu.be/4166ExAnxmo)
2. [Creating and Managing a GPG Key Pair - YouTube](https://www.youtube.com/watch?v=4166ExAnxmo)

After configuring Git signed commits, you have to ensure that all the commits which are part of this PR are signed.

**Pull request closed without merging**
