### PR TITLE
Add notation discovery workflow for new identities

### PR DESCRIPTION
**Pull request by SteveLasker**
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Comment by nate-double-u** [comment]
deploy preview: https://deploy-preview-73--notarydev.netlify.app/docs/notation/v0.7.1-alpha.2/discovery-and-configuration/

I'd suggest removing the `/content/en/docs/notation)/v0.0.0/` folder with this PR too as you're creating the `v0.7.1-alpha.2` directory :)

**Comment by SteveLasker** [comment]
@nate-double-u, thanks. I also noticed the heading gets duped with the preview. 
Do I not have a heading 1, and use the `title:` property as heading 1?

Looking at this PR, that seems like the pattern: https://github.com/notaryproject/notaryproject.dev/pull/27/files

**Review by nate-double-u — APPROVED** [review]
/lgtm
(from a structure point of view -- I haven't reviewed the content. Let me know if you'd like a copy edit pass 🙂)

**Comment by nate-double-u** [comment]
> @nate-double-u, thanks. I also noticed the heading gets duped with the preview. Do I not have a heading 1, and use the `title:` property as heading 1?
> 
> Looking at this PR, that seems like the pattern: https://github.com/notaryproject/notaryproject.dev/pull/27/files

Correct, I don't there is any need for an initial header as the title styling takes care of it. Usually I'd avoid any H1 headings on a page because then it fights the title for hierarchy.

**Comment by zr-msft** [comment]
@SteveLasker @toddysm is this PR still relevant or should it be closed?

**Comment by zr-msft** [comment]
Closing for now due to inactivity

**Pull request closed without merging**
