### PR TITLE
corrected the spelling in  2023 blog section

### LINKED ISSUE #257: Spelling and Grammatical mistake in 2023 blog section.
Mistake -
Shoule be `reported` instead of `disclosed`

---

Screenshot from 2023-05-24 03-46-11

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
Fixes #257
In the sentence "The vulnerability has been disclosed in GHSA-87x9-7grx-m28v," `disclosed` should be changed to `reported.`

### CODE REVIEW

**Comment by zr-msft** [comment]
@Vikash-8090-Yadav i think you pulled in some extra commits to this PR: https://github.com/notaryproject/notaryproject.dev/pull/258#commits-pushed-59c007f

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav i think you pulled in some extra commits to this PR: [#258 (commits)](https://github.com/notaryproject/notaryproject.dev/pull/258#commits-pushed-59c007f)

Hey @zr-msft  sir, are u talking about this first commit? if yes, then I don't know how it linked with my PR. When I pushed the commit and raised the PR it automatically show that commit. Can u please help me to troubleshoot this? 
Thanks !!

**Comment by FeynmanZhou** [comment]
@Vikash-8090-Yadav  Thanks. I think these changes are not necessary. In this fuzzing security test blog context, `disclosed` is also fine.

**Comment by Vikash-8090-Yadav** [comment]
Hey @FeynmanZhou Thanks for the info, Can u please check the other correction which i have made in this commit . If that  seems to be legit then I will make pr for that alone . Thanks !!

**Comment by zr-msft** [comment]
Thank you @Vikash-8090-Yadav for the contribution!

Based on [comments](https://github.com/notaryproject/notaryproject.dev/pull/258#issuecomment-1562777033) from @FeynmanZhou closing PR

**Pull request closed without merging**
