### PR TITLE
Added Version control for documentation

### PR DESCRIPTION
**Pull request by sanjayk0508**
Added version control for documentation. Currently, the name of the current version in the drop-down is set as `Master (v0.1)`, and the version menu is named `version_menu: "v0.1"`. Ensure to edit the names accordingly when updating to a new version.

Fixes: #370 #350

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@sanjayk0508 Could you please help change the version control drop-down list to:

Version (menu name)
- main, points to notaryproject.dev
- v1.1, points to v1-1.notaryproject.dev
- v1.0, points to v1-1.notaryproject.dev

**Review by FeynmanZhou — COMMENTED** [review]
See my comment below

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by akashsinghal** [comment]
> @sanjayk0508 Could you please help change the version control drop-down list as follows:
> 
> Version (menu name)
> 
> * **main**, points to notaryproject.dev
> * **v1.1**, points to v1-1.notaryproject.dev
> * **v1.0**, points to v1-0.notaryproject.dev

Do we want `notaryproject.dev` to point to v1.1 instead? I see here that it currently points to main branch version

**Review by yizha1 — APPROVED** [review]
LGTM

Thanks @sanjayk0508

**Comment by FeynmanZhou** [comment]
> > @sanjayk0508 Could you please help change the version control drop-down list as follows:
> > Version (menu name)
> > 
> > * **main**, points to notaryproject.dev
> > * **v1.1**, points to v1-1.notaryproject.dev
> > * **v1.0**, points to v1-0.notaryproject.dev
> 
> Do we want `notaryproject.dev` to point to v1.1 instead? I see here that it currently points to main branch version

@akashsinghal Thanks for your suggestion. `vX-Y.notaryproject.dev` should be pointed to the stable release as it will create a versioned link for the stable release. This avoid broken links in the stable release content. Instead, `notaryproject.dev` will be pointed to the default `main` branch because it has no version info.

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Pull request merged**
