### PR TITLE
Add Samir Kakkar as NotaryProject.dev maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Samir Kakkar as a seed maintainer of NotaryProject.dev based on their activity and as per - https://github.com/notaryproject/notaryproject.dev/issues/127

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Comment by FeynmanZhou** [comment]
Close this PR as it was covered by https://github.com/notaryproject/notaryproject.dev/pull/137

**Pull request closed without merging**
