### PR TITLE
Grammartical mistake

### LINKED ISSUE #231: Grammatical mistake in quickstart.md
Hey i  found one grammatical mistake in docs . 

Directory -> https://github.com/Vikash-8090-Yadav/notaryproject.dev/blob/main/content/en/docs/quickstart.md
------
Screenshot from 2023-05-20 19-44-41
------

## 
Improved sentence is `which registries are compatible with Notary`

 
The change from "registries" to "which registries" improves the clarity and readability of the sentence. It specifies that the reader should refer to the list of registries that are compatible with Notary.

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
Fixes #231 

spelling mistake in quickstart.md

Improved sentence is `which registries are compatible with Notary`

 
The change from "registries" to "which registries" improves the clarity and readability of the sentence. It specifies that the reader should refer to the list of registries that are compatible with Notary.

### CODE REVIEW

**Review by toddysm — APPROVED** [review]

**Review by yizha1 — APPROVED** [review]
LGTM

**Comment by yizha1** [comment]
@Vikash-8090-Yadav you need to sign the commits, please refer to guideline https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by Vikash-8090-Yadav** [comment]
@yizha1 please check once.I added the Gpg key and also sign in the commit.

**Review by zr-msft — APPROVED** [review]
LGTM

**Pull request merged**
