### PR TITLE
Added float copy button for the command lines #193

### PR DESCRIPTION
**Pull request by Sumitmaithani**
**Description**

This PR addresses issue [#193 ](https://github.com/notaryproject/notaryproject.dev/issues/193) by adding a floating copy button for command lines in order to improve user experience and make it easier to copy long command lines.

Quickstart_ Sign and validate a container image _ Notary _ Signing and verifying artifacts  Safeguarding the software delivery security from development to deployment  - Google Chrome 5_11_2023 11_24_49 PM (2)
Quickstart_ Sign and validate a container image _ Notary _ Signing and verifying artifacts  Safeguarding the software delivery security from development to deployment  - Google Chrome 5_11_2023 11_25_27 PM (2)

### CODE REVIEW

**Comment by zr-msft** [comment]
@Sumitmaithani  FYI, everything under `cli-referecnce` is auto-generated and will be overwritten when a new CLI version is available. I'm working on a PR now for the MD generation and will include the `console` label in the code fence.

Otherwise, LGTM

**Review by zr-msft — APPROVED** [review]

**Review by yizha1 — APPROVED** [review]
LGTM. Thanks @Sumitmaithani

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
@Sumitmaithani  Notary project repositories require signed commits, could you please refer to [commit signatures verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) to sigg all your commits?

**Comment by Sumitmaithani** [comment]
Thanks for letting me know, @FeynmanZhou. I've completed my commit signature verification and signed all my commits.

**Pull request merged**
