### PR TITLE
Updated quickstart.md file

### LINKED ISSUE #283: Update the quickstart guide "docker inspect" section to rightly inspect the image digest for signing
I followed the quickstart guide to sign and validate a container image. Later, I removed the registry using the `docker rm -f registry` command.

During a second attempt to sign and validate the image, I noticed that the `docker inspect localhost:5001/net-monitor:v1 -f '{{ .Id }}'` command continued to show the digest value of the previous image: `sha256:64e93xxxxxxxda0ab`, instead of the newly created image's digest: `sha256:cae906b8xxxxxxxx41786`

To resolve this issue, @FeynmanZhou suggested using the `docker inspect --format='{{index .RepoDigests 0}}' localhost:5001/net-monitor:v1` command. This correctly outputs the digest of the new image.

I will submit a PR with the necessary updates to the quickstart guide for review.

### PR DESCRIPTION
**Pull request by Roseline-Bassey**
This PR fixed #283 

I have updated the docker inspect command in the quickstart guide to rightly inspect the sample image.

### CODE REVIEW

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
Thanks @Roseline-Bassey for taking this issue and fixing it.

**Comment by FeynmanZhou** [comment]
@yizha1 @zr-msft @iamsamirzon @priteshbandi Could you pls also review it?

**Review by yizha1 — APPROVED** [review]
Thanks @Roseline-Bassey, nice catch. LGTM

**Comment by Roseline-Bassey** [comment]
You're welcome @FeynmanZhou and @yizha1

**Pull request merged**
