### PR TITLE
Refactoring folder structure to use project names

### LINKED ISSUE #30: Update docs folder structure to reflect 3 projects
Instead of `/content/en/docs/v1` and `/content/en/docs/v2`, use the project name for organizing the folder structure.

### PR DESCRIPTION
**Pull request by nate-double-u**
fixes #30 

Deploy previews:
* https://deploy-preview-31--notarydev.netlify.app/
* https://deploy-preview-31--notarydev.netlify.app/community/
* https://deploy-preview-31--notarydev.netlify.app/community/meeting-notes/
* https://deploy-preview-31--notarydev.netlify.app/docs/

### CODE REVIEW

**Comment by nate-double-u** [comment]
I've removed the versioning code for now as it'll be complex to version three projects separately--I feel like it'll be better to do it as we need to, and not before. 

I've also removed the stubs from the navigation, and linked directly to the github repos for documentation for now. @SteveLasker could you please double check that these links are correct?

**Comment by nate-double-u** [comment]
I've made some changes based on a feedback session with @SteveLasker & @mnm678.

This new folder structure more closely follows the proposed info architecture (https://github.com/notaryproject/notaryproject.dev/issues/23) laid out in the [shared notes file](https://hackmd.io/@nate-double-u/H1JkSDYWF).

**Comment by SteveLasker** [comment]
In the docs: https://deploy-preview-31--notarydev.netlify.app/docs/, I don't see the file that sets the ordering.
Can this be 
- notation
- notation-go
- tuf

**Comment by nate-double-u** [comment]
> In the docs: https://deploy-preview-31--notarydev.netlify.app/docs/, I don't see the file that sets the ordering. Can this be
> 
>     * notation
> 
>     * notation-go
> 
>     * tuf
> 
> 
> Otherwise, LGTM

I just noticed that and have fixed it.

**Review by SteveLasker — APPROVED** [review]
LGTM

A nit, and we can do in a subsequent PR.
For the list of docs/projects (notation, notation-go, tuf), I wonder if the bulleted list should describe what each is

- notation - the cli for signing and verifying a notary v2 signature 
- notation-go-lib - a set of go libraries for incorporating signing and verification in other clis
- tuf - prototypes for meta-data support, enabling compromise resilience, revocation of keys and artifacts, and timeliness guarantees

**Comment by nate-double-u** [comment]
We can add descriptions for sure. We'll need to open another issue to move the meeting notes archive in as well -- not sure where you want to put that issue though @SteveLasker .

**Pull request merged**
