### PR TITLE
Updated quickstart guide to fix #283

### LINKED ISSUE #283: Update the quickstart guide "docker inspect" section to rightly inspect the image digest for signing
I followed the quickstart guide to sign and validate a container image. Later, I removed the registry using the `docker rm -f registry` command.

During a second attempt to sign and validate the image, I noticed that the `docker inspect localhost:5001/net-monitor:v1 -f '{{ .Id }}'` command continued to show the digest value of the previous image: `sha256:64e93xxxxxxxda0ab`, instead of the newly created image's digest: `sha256:cae906b8xxxxxxxx41786`

To resolve this issue, @FeynmanZhou suggested using the `docker inspect --format='{{index .RepoDigests 0}}' localhost:5001/net-monitor:v1` command. This correctly outputs the digest of the new image.

I will submit a PR with the necessary updates to the quickstart guide for review.

### PR DESCRIPTION
**Pull request by Roseline-Bassey**
This PR fixed #283 

I have updated the `docker inspect` command in the quickstart guide to rightly inspect the sample image.
I also updated its output.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@Roseline-Bassey Thanks. Could you resolve the DCO issue by signing your commits? See https://github.com/notaryproject/notaryproject.dev/pull/285/checks?check_run_id=14249077315

**Comment by zr-msft** [comment]
@Roseline-Bassey changes to the quickstart LGTM, but what are the changes to the troubleshooting.md? They seem unrelated to the PR description and linked issue.

**Review by iamsamirzon — DISMISSED** [review]

**Comment by Roseline-Bassey** [comment]
> @Roseline-Bassey changes to the quickstart LGTM, but what are the changes to the troubleshooting.md? They seem unrelated to the PR description and linked issue.

Hi @zr-msft , thanks for the feedback. The changes to troubleshooting.md can be found[ here](https://github.com/notaryproject/notaryproject.dev/pull/285)

**Comment by zr-msft** [comment]
@Roseline-Bassey thank you for linking to the other PR, but you need to fix both of these PRs:

- #283 should contain ONLY your quickstart fix
- #285 should contain ONLY your troubleshooting fix

**Comment by Roseline-Bassey** [comment]
> @Roseline-Bassey thank you for linking to the other PR, but you need to fix both of these PRs:
> 
> * [Update the quickstart guide "docker inspect" section to rightly inspect the image digest for signing #283](https://github.com/notaryproject/notaryproject.dev/issues/283) should contain ONLY your quickstart fix
> * [Updated and modified some sections of troubleshooting docs #285](https://github.com/notaryproject/notaryproject.dev/pull/285) should contain ONLY your troubleshooting fix

I acknowledge the mix-up. I'm working on fixing both PR. Thanks for your feedback.

**Comment by Roseline-Bassey** [comment]
Hi, everyone

I have fixed all issues related to this PR in a [new PR.](https://github.com/notaryproject/notaryproject.dev/pull/289) Please kindly have a look.

**Comment by FeynmanZhou** [comment]
@Roseline-Bassey Let's close PR as the changes has been included in another PR.

**Pull request closed without merging**
