### PR TITLE
chore: update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hugo-sid**
I came to know about Notary project repositories requiring signed commits from this comment https://github.com/notaryproject/notaryproject.dev/pull/201#issuecomment-1547300966. I thought it's a good idea to mention it in the contribution guidelines.

### CODE REVIEW

**Comment by yizha1** [comment]
Thanks @hugo-sid, the contributing guide is tracked under https://github.com/notaryproject/.github/blob/main/CONTRIBUTING.md

There is ongoing PR to update contributing guide https://github.com/notaryproject/.github/pull/25

**Comment by hugo-sid** [comment]
Thanks @yizha1. 

> the contributing guide is tracked under https://github.com/notaryproject/.github/blob/main/CONTRIBUTING.md

Then, I guess, a mention to https://github.com/notaryproject/.github/blob/main/CONTRIBUTING.md in this repo's `CONTRIBUTING.md` would suffice. Let me know your thoughts.

**Review by zr-msft — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM

**Pull request merged**
