### PR TITLE
Header text overflow has been resolved in mobile view.

### PR DESCRIPTION
**Pull request by PranitPatil03**
The issue is #199

Problem: The important message/notification which is above the navigation bar, collides with the navigation bar, in the mobile view

Solution: I have just increased the height of that important message div and also make it text-justify.

### CODE REVIEW

**Comment by PranitPatil03** [comment]
Changes 

Website - The font size of the message is reduced to 15 px so that it fits in one line.

<details><summary>Details</summary>
<p>

screencapture-deploy-preview-212-notarydev-netlify-app-2023-05-16-23_19_27

</p>
</details> 

Mobile -  Increase the height of the message container to ensure that the message is displayed clearly.

<details><summary>Details</summary>
<p>

WhatsApp Image 2023-05-16 at 23 37 09

</p>
</details>

**Comment by lata-11** [comment]
Hello @PranitPatil03. Thank you for working on this. The changes look good to me.

**Comment by lata-11** [comment]
Hello @PranitPatil03. Thank you for working on this. The changes look good to me.

**Comment by PranitPatil03** [comment]
hello @FeynmanZhou 👋

Can you review these changes?

**Pull request closed without merging**
