### PR TITLE
doc: update notice

### PR DESCRIPTION
**Pull request by shizhMSFT**
Update notice block for better view in Hugo.

### CODE REVIEW

**Comment by shizhMSFT** [comment]
## Important Block
### Before
image

### After
image

**Comment by shizhMSFT** [comment]
## Warning Block
### Before
image

### After
image

**Comment by shizhMSFT** [comment]
## Note Block
### Before
image
image

### After
image
image

**Review by zr-msft — APPROVED** [review]
Nice work! LGTM

**Review by FeynmanZhou — DISMISSED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM

**Comment by yizha1** [comment]
Thanks @shizhMSFT

**Comment by yizha1** [comment]
@shizhMSFT need sign the commits ;-)

**Review by yizha1 — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Pull request merged**
