### PR TITLE
docs: update quickstart.md

### PR DESCRIPTION
**Pull request by junczhu**
A spacing fix

### CODE REVIEW

**Comment by zr-msft** [comment]
@junczhu thank you for the suggestion!

Before we consider merging:
- This seems like a spacing fix. Does the current code block lead to any issues/errors when going through the doc?
- Have you tested the whole doc with you proposed changes to ensure everything still works?

**Comment by junczhu** [comment]
> @junczhu thank you for the suggestion!
> 
> Before we consider merging:
> 
> * This seems like a spacing fix. Does the current code block lead to any issues/errors when going through the doc?
> * Have you tested the whole doc with you proposed changes to ensure everything still works?

@zr-msft there is no issue coming with either the current code block or the proposed changes

**Review by zr-msft — APPROVED** [review]
Thank you @junczhu

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Pull request merged**
